### ISSUE TITLE
Is RHEL 8 supported?

### ISSUE THREAD

**Issue by flyemsafe** [antonioromito/rhsm-api-client#10]
Running this on RHEL 8.2 I get the below error.

```
Traceback (most recent call last):
  File "/usr/local/bin/rhsm-cli", line 4, in <module>
    __import__('pkg_resources').run_script('rhsm-cli==1.0', 'rhsm-cli')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'rhsm-cli==1.0' distribution was not found and is required by the application
```

**Comment by antonioromito** [comment]
Hi @flyemsafe, I'm working on it still had no luck on RHEL8.2...
I'll keep you posted
