### ISSUE TITLE
failed to save token

### ISSUE THREAD

**Issue by flyemsafe** [antonioromito/rhsm-api-client#7]
Not sure if this is an issue with the token or perhaps change with the API.

Got this error with a newly generated token.

```
$ .python/rhsm_cli/bin/rhsm-cli -t rhsm_token savetoken
Traceback (most recent call last):
  File ".python/rhsm_cli/bin/rhsm-cli", line 4, in <module>
    __import__('pkg_resources').run_script('rhsm-cli==1.0', 'rhsm-cli')
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/rhsm_cli-1.0-py3.6.egg/EGG-INFO/scripts/rhsm-cli", line 25, in <module>
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/rhsm_cli-1.0-py3.6.egg/rhsm/client.py", line 194, in main
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/rhsm_cli-1.0-py3.6.egg/rhsm/client.py", line 44, in __init__
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/rhsm_cli-1.0-py3.6.egg/rhsm/client.py", line 61, in get_service
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/rhsm_cli-1.0-py3.6.egg/rhsm/service.py", line 39, in refresh_token
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/home/admin/qubinode-installer/.python/rhsm_cli/lib64/python3.6/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Invalid refresh token
```

**Comment by antonioromito** [comment]
@flyemsafe sorry for the late answer, you are perfectly right! Thank you so much for spotting this out.

**Comment by antonioromito** [comment]
Fixed with the latest merge.
